//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageCalculatorTcpClient.MortgageCalculatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MortgageCalculatorServiceReference.IMortgageCalculator")]
    public interface IMortgageCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMortgageCalculator/ComputeMortgage", ReplyAction="http://tempuri.org/IMortgageCalculator/ComputeMortgageResponse")]
        MortgageCalculatorServiceLibrary.Mortgage ComputeMortgage(double purchasePrice, double interestRate, int amortization, double taxes, double percentDown);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMortgageCalculator/ComputeMortgage", ReplyAction="http://tempuri.org/IMortgageCalculator/ComputeMortgageResponse")]
        System.Threading.Tasks.Task<MortgageCalculatorServiceLibrary.Mortgage> ComputeMortgageAsync(double purchasePrice, double interestRate, int amortization, double taxes, double percentDown);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMortgageCalculatorChannel : MortgageCalculatorTcpClient.MortgageCalculatorServiceReference.IMortgageCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MortgageCalculatorClient : System.ServiceModel.ClientBase<MortgageCalculatorTcpClient.MortgageCalculatorServiceReference.IMortgageCalculator>, MortgageCalculatorTcpClient.MortgageCalculatorServiceReference.IMortgageCalculator {
        
        public MortgageCalculatorClient() {
        }
        
        public MortgageCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MortgageCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MortgageCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MortgageCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MortgageCalculatorServiceLibrary.Mortgage ComputeMortgage(double purchasePrice, double interestRate, int amortization, double taxes, double percentDown) {
            return base.Channel.ComputeMortgage(purchasePrice, interestRate, amortization, taxes, percentDown);
        }
        
        public System.Threading.Tasks.Task<MortgageCalculatorServiceLibrary.Mortgage> ComputeMortgageAsync(double purchasePrice, double interestRate, int amortization, double taxes, double percentDown) {
            return base.Channel.ComputeMortgageAsync(purchasePrice, interestRate, amortization, taxes, percentDown);
        }
    }
}
